# Site settings
title: Baltimore Open Air
description: > # this means to ignore newlines until "baseurl:"
 Baltimore Open Air homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://baltimoreopenair.github.io" # the base hostname & protocol for your site
twitter_username: bmoreopenair
github_username:  BaltimoreOpenAir
markdown: kramdown
highlighter: rouge
gems: ['jekyll/scholar']

# Build settings
exclude: ['_drafts', 'convert_notebook.sh', 'nbconvert-jekyll-post.tpl', 'nbconvert_utils.py', 'nbconvert_config.py', 'readings', 'Makefile']
include: ['readings.pdf']
